### ISSUE TITLE
can't create my-app

### ISSUE THREAD

**Issue by Ujjavalkc13** [shystruk/create-react-redux-app-structure#11]
![image](https://user-images.githubusercontent.com/37399220/37453724-97377d8e-285e-11e8-820c-65715d47451a.png)

i am getting error when i insert command create-react-redux-app-structure my-app

**Comment by shystruk** [comment]
Hi @Ujjavalkc13 
Thank you for being interested in create-react-redux-app-structure 👍

Which nodejs and npm versions do you have installed?
`node -v` `npm -v`

Thanks,
Vasyl

**Comment by shystruk** [comment]
While I will find why that issue has happened you can clone the project (git clone https://github.com/shystruk/create-react-redux-app-structure.git) or download it and keep discovering :)

**Comment by shystruk** [comment]
Hi @Ujjavalkc13 
You are not responding for a while. Hope the issue is not actual for you anymore if not please add a comment.
Thanks! 👍

**Comment by IanDuran** [comment]
I'm having the same issue
I'm using node 8.10.0 and npm 5.6.0

**Comment by shystruk** [comment]
@IanDuran  @Ujjavalkc13 
Hey guys,
I checked, have the same error but my-app was created and the app works fine.
You can omit that error. I guess the issue is on one of the npm packeges for current node version. 

I use 6.14.1 it is stable and there is no error. You can downgrade - https://nodejs.org/download/release/v6.14.1/
